const TelegramBot = require('node-telegram-bot-api');
const express = require('express');
const bodyParser = require('body-parser');

const token = process.env.BOT_TOKEN;
const bot = new TelegramBot(token);

let botUsername = process.env.BOT_USERNAME || '';
bot.getMe().then(me => {
    if (me && me.username) {
        botUsername = me.username;
        console.log(`Bot Username loaded: @${botUsername}`);
    }
}).catch(err => console.error("Failed to get bot username:", err));

const app = express();
app.use(bodyParser.json());

// In-memory stores for media, sessions, and passwords
const mediaStore = new Map();
const pendingUploads = new Map();
const mediaPasswords = new Map();
const userPasswordInputs = new Map();

const formatSize = (bytes) => {
    if (!bytes) return '<b>N/A</b>';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return `<code>${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}</code>`;
};

const strings = {
    welcome: (name) => 
        `<blockquote>👋 <b>Hello, ${name}!</b>\n\n` +
        `Welcome to <b>TG Meta69 Bot!</b> Explore user & media information, manage files securely with password protection, and download TikTok videos with ease. 🚀</blockquote>`,
    
    help: 
        `<blockquote>👑 <b>TG Meta69 Bot - Help Menu</b>\n\n` +
        `📋 <b>User Commands:</b>\n` +
        `>  · /start - Start the bot\n` +
        `>  · /tiktok - Download TikTok video\n` +
        `>  · /help - Show this help menu\n` +
        `>  · /id @username - Get ID by username\n` +
        `>  · /stat - Check bot statistics & status\n\n` +
        `📱 <b>Keyboard Buttons:</b>\n` +
        `>  · 👤 User Info - Get any user's ID\n` +
        `>  · 🆔 My Info - Get your own ID details\n` +
        `>  · ☎️ Support - Contact developer\n\n` +
        `✨ <b>Special Features:</b>\n` +
        `>  · 📩 Forward Msg → Get source & media ID\n` +
        `>  · 📷 Send Photo/Video/File/Doc → Generate Secure Telegram Start Links with/without Password!\n` +
        `>  · 🎥 TikTok Video → Send link for direct chat buffer video download (Under 30MB)</blockquote>`,

    stat: (mediaCount, lat) => 
        `<blockquote>📊 <b>Bot Statistics & Status</b>\n\n` +
        `⚡ Latency: <code>${lat}ms</code>\n` +
        `🤖 Status: <b>Online</b>\n` +
        `🕒 Uptime: <b>Always Active</b>\n` +
        `📂 Stored Media: <code>${mediaCount} items</code>\n` +
        `⚙️ Version: <code>${process.version}</code></blockquote>`,

    id_err: 
        `<blockquote>ℹ️ <b>Use This Command</b>\n\n` +
        `Please use the command like this:\n` +
        `>  · /id @username\n` +
        `>  · Or reply to a message with /id</blockquote>`,

    guide: 
        `<blockquote>ℹ️ <b>How to use this bot:</b>\n\n` +
        `📱 Use keyboard buttons to get IDs\n` +
        `📎 Send any file to get its secure Telegram Start & Share links\n` +
        `📩 Forward messages to get source ID\n` +
        `🔗 Send TikTok or media links</blockquote>`
};

const mainKeyboard = {
    reply_markup: {
        keyboard: [
            [{ text: '👤 User Info', request_users: { request_id: 101, user_is_bot: false } }],
            [{ text: '🆔 My Info' }, { text: '☎️ Support' }]
        ],
        resize_keyboard: true
    },
    parse_mode: 'HTML'
};

// Helper function to send media securely via Telegram Bot
async function handleMediaPayload(chatId, mediaData, providedPwd = '') {
    if (mediaData) {
        const payloadId = mediaData.payloadId;
        const reqPwd = payloadId ? mediaPasswords.get(payloadId) : null;

        if (reqPwd && providedPwd !== reqPwd) {
            userPasswordInputs.set(chatId, { payloadId, mediaData });
            await bot.sendMessage(chatId, `<blockquote>🔒 <b>Password Required</b>\n\nThis media is protected with a password. Please type and send the password in chat to access it.</blockquote>`, { parse_mode: 'HTML' });
            return false;
        }

        const generatorName = mediaData.user ? (mediaData.user.first_name || 'Unknown User') : 'Unknown User';
        const generatorId = mediaData.user ? mediaData.user.id : 'N/A';
        const generatorUsername = mediaData.user && mediaData.user.username ? `@${mediaData.user.username}` : 'No Username';
        const userLinkHtml = mediaData.user && mediaData.user.username ? `<a href="t.me/${mediaData.user.username}">${generatorName}</a>` : `<code>${generatorName}</code>`;

        const headerText = `<blockquote>👤 <b>Generated By:</b> ${userLinkHtml}\n🆔 ID: <code>${generatorId}</code>\n🏷️ Username: ${generatorUsername}\n\n</blockquote>`;

        if (mediaData.fileType === 'photo' && mediaData.fileId) {
            await bot.sendPhoto(chatId, mediaData.fileId, {
                caption: headerText + `<blockquote>✨ <b>Here is your requested photo!</b></blockquote>`,
                parse_mode: 'HTML'
            });
            return true;
        } else if (mediaData.fileType === 'video' && mediaData.fileId) {
            await bot.sendVideo(chatId, mediaData.fileId, {
                caption: headerText + `<blockquote>✨ <b>Here is your requested video!</b></blockquote>`,
                parse_mode: 'HTML'
            });
            return true;
        } else if (mediaData.fileType === 'document' && mediaData.fileId) {
            await bot.sendDocument(chatId, mediaData.fileId, {
                caption: headerText + `<blockquote>✨ <b>Here is your requested document!</b></blockquote>`,
                parse_mode: 'HTML'
            });
            return true;
        } else if (mediaData.fileType === 'audio' && mediaData.fileId) {
            await bot.sendAudio(chatId, mediaData.fileId, {
                caption: headerText + `<blockquote>✨ <b>Here is your requested audio!</b></blockquote>`,
                parse_mode: 'HTML'
            });
            return true;
        } else if (mediaData.fileType === 'voice' && mediaData.fileId) {
            await bot.sendVoice(chatId, mediaData.fileId, {
                caption: headerText + `<blockquote>✨ <b>Here is your requested voice!</b></blockquote>`,
                parse_mode: 'HTML'
            });
            return true;
        } else if (mediaData.fileType === 'sticker' && mediaData.fileId) {
            await bot.sendSticker(chatId, mediaData.fileId);
            return true;
        }
    }

    await bot.sendMessage(chatId, `<blockquote>❌ <b>Link Expired or Not Found</b>\n\nThis media link has expired or is invalid. Please send the media to the bot again to get a fresh link.</blockquote>`, { parse_mode: 'HTML' });
    return false;
}

app.post(`/api/webhook`, async (req, res) => {
    if (!req.body || (!req.body.message && !req.body.callback_query)) {
        if (!res.headersSent) res.status(200).send('OK');
        return;
    }

    try {
        const update = req.body;
        
        if (update.callback_query) {
            const callbackQuery = update.callback_query;
            const msg = callbackQuery.message;
            if (msg) {
                const chatId = msg.chat.id;
                const data = callbackQuery.data;

                if (data === 'help_menu') {
                    await bot.editMessageText(strings.help, {
                        chat_id: chatId,
                        message_id: msg.message_id,
                        parse_mode: 'HTML',
                        reply_markup: {
                            inline_keyboard: [
                                [{ text: '🏠 Back to Start', callback_data: 'back_start' }]
                            ]
                        }
                    });
                    await bot.answerCallbackQuery(callbackQuery.id);
                } else if (data === 'back_start') {
                    await bot.editMessageText(strings.welcome(callbackQuery.from.first_name), {
                        chat_id: chatId,
                        message_id: msg.message_id,
                        parse_mode: 'HTML',
                        reply_markup: {
                            inline_keyboard: [
                                [{ text: 'ℹ️ Help Menu', callback_data: 'help_menu' }]
                            ]
                        }
                    });
                    await bot.answerCallbackQuery(callbackQuery.id);
                } else if (data.startsWith('pwd_ask_')) {
                    const origMsgId = data.split('_')[2];
                    userPasswordInputs.set(chatId, { mode: 'setting_pwd', origMsgId });
                    await bot.answerCallbackQuery(callbackQuery.id, { text: 'Please type the password in chat.' });
                    await bot.sendMessage(chatId, `<blockquote>🔐 <b>Set Media Password</b>\n\nPlease type and send the password you want to set for this file.</blockquote>`, { parse_mode: 'HTML' });
                } else if (data.startsWith('pwd_none_')) {
                    const origMsgId = data.split('_')[2];
                    const pendingKey = `${chatId}_${origMsgId}`;
                    const fileData = pendingUploads.get(pendingKey);

                    if (!fileData) {
                        await bot.answerCallbackQuery(callbackQuery.id, { text: '❌ Session expired. Please resend the file.', show_alert: true });
                    } else {
                        await bot.answerCallbackQuery(callbackQuery.id, { text: '⏳ Generating Telegram links...' });
                        await processTelegramMediaShare(chatId, msg.message_id, fileData, callbackQuery.from, null);
                    }
                }
            }
        }

        const msg = update.message;
        if (msg) {
            const chatId = msg.chat.id;
            const text = msg.text || msg.caption || "";
            const entities = (msg.entities || []).concat(msg.caption_entities || []);

            // Check if user is typing password
            if (userPasswordInputs.has(chatId) && text && !text.startsWith('/')) {
                const state = userPasswordInputs.get(chatId);
                if (state.mode === 'setting_pwd') {
                    const password = text.trim();
                    const pendingKey = `${chatId}_${state.origMsgId}`;
                    const fileData = pendingUploads.get(pendingKey);
                    userPasswordInputs.delete(chatId);

                    if (!fileData) {
                        await bot.sendMessage(chatId, `<blockquote>❌ <b>Session Expired.</b> Please resend the file.</blockquote>`, { parse_mode: 'HTML' });
                    } else {
                        await bot.sendMessage(chatId, `<blockquote>⏳ <b>Generating protected Telegram links...</b></blockquote>`, { parse_mode: 'HTML' });
                        await processTelegramMediaShare(chatId, msg.message_id - 1, fileData, msg.from, password);
                    }
                    if (!res.headersSent) res.status(200).send('OK');
                    return;
                } else if (state.payloadId && state.mediaData) {
                    const password = text.trim();
                    const reqPwd = mediaPasswords.get(state.payloadId);
                    userPasswordInputs.delete(chatId);

                    if (password === reqPwd) {
                        await handleMediaPayload(chatId, state.mediaData, password);
                    } else {
                        await bot.sendMessage(chatId, `<blockquote>❌ <b>Incorrect Password!</b> Access denied.</blockquote>`, { parse_mode: 'HTML' });
                    }
                    if (!res.headersSent) res.status(200).send('OK');
                    return;
                }
            }

            if (text.startsWith('/start')) {
                const parts = text.split(' ');
                if (parts.length > 1) {
                    const param = parts[1];
                    if (param.startsWith('srmeta_') || param === 'sr69') {
                        if (mediaStore.has(param)) {
                            await handleMediaPayload(chatId, mediaStore.get(param));
                        } else {
                            await bot.sendMessage(chatId, `<blockquote>✨ <b>TG Meta69 Bot Media Hub</b>\n\nWelcome via bot share link! Send any photo, video, or document to generate share links.</blockquote>`, { parse_mode: 'HTML' });
                        }
                    }
                } else {
                    await bot.sendMessage(chatId, strings.welcome(msg.from.first_name), mainKeyboard);
                }
            }
            else if (text === '/help') {
                await bot.sendMessage(chatId, strings.help, { 
                    parse_mode: 'HTML',
                    reply_markup: {
                        inline_keyboard: [
                            [{ text: '🏠 Back to Start', callback_data: 'back_start' }]
                        ]
                    }
                });
            }
            else if (text === '/stat') {
                const latency = Math.floor(Math.random() * 10) + 40;
                const effectiveCount = Math.ceil(mediaStore.size / 2);
                await bot.sendMessage(chatId, strings.stat(effectiveCount, latency), { parse_mode: 'HTML' });
            }
            else if (text.startsWith('/id')) {
                const args = text.split(' ');
                if (msg.reply_to_message) {
                    const ruid = msg.reply_to_message.from.id;
                    await bot.sendMessage(chatId, `<blockquote>🆔 <b>Sender ID</b>\n\n🆔 User ID: <code>${ruid}</code></blockquote>`, { parse_mode: 'HTML' });
                } else if (args.length > 1) {
                    const target = args[1].startsWith('@') ? args[1] : '@' + args[1];
                    try {
                        const chat = await bot.getChat(target);
                        await bot.sendMessage(chatId, `<blockquote>🔍 <b>Lookup Result</b>\n\n🆔 ID: <code>${chat.id}</code>\n👤 Name: <code>${chat.first_name || chat.title}</code></blockquote>`, { parse_mode: 'HTML' });
                    } catch (e) {
                        await bot.sendMessage(chatId, `<blockquote>❌ <b>Error</b>\n\nUsername not found.</blockquote>`, { parse_mode: 'HTML' });
                    }
                } else {
                    await bot.sendMessage(chatId, strings.id_err, { parse_mode: 'HTML' });
                }
            }
            else if (text === '🆔 My Info') {
                const u = msg.from;
                await bot.sendMessage(chatId, `<blockquote>🆔 <b>Your Information</b>\n\n` +
                    `🆔 ID: <code>${u.id}</code>\n👤 Name: <code>${u.first_name}</code>\n🏷️ User: @${u.username || 'N/A'}\n⭐ Prem: ${u.is_premium ? '✅' : '❌'}</blockquote>`, { parse_mode: 'HTML' });
            }
            else if (text === '☎️ Support') {
                await bot.sendMessage(chatId, `<blockquote>🛡️ <b>Need help or found a bug?</b>\n\n` +
                    `· If you encounter any issues, have questions, or want to suggest a new feature, feel free to reach out!\n` +
                    `· Contact my developer: <b>@srshihab69</b></blockquote>`, { parse_mode: 'HTML', reply_markup: { inline_keyboard: [[{ text: '👨‍💻 Developer', url: 'https://t.me/srshihab69' }]] } });
            }
            else if (text.toLowerCase().includes('tiktok.com') || text.toLowerCase().includes('vm.tiktok.com')) {
                let videoDownloadUrl = "";
                let processingMsg = null;

                try {
                    processingMsg = await bot.sendMessage(chatId, `<blockquote>⏳ <b>Processing TikTok video...</b></blockquote>`, { parse_mode: 'HTML' });

                    const urlRegex = /https?:\/\/(?:[a-zA-Z0-9-]+\.)?(?:vm\.tiktok\.com|tiktok\.com)\/[^\s]+/g;
                    const foundUrls = text.match(urlRegex) || [];
                    let targetUrl = foundUrls.find(url => !url.includes('tiktoklite')) || foundUrls[0] || text.trim();

                    if (targetUrl.includes('?')) {
                        targetUrl = targetUrl.split('?')[0];
                    }

                    const apiRes = await fetch(`https://www.tikwm.com/api/?url=${encodeURIComponent(targetUrl)}`, {
                        headers: { 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)' }
                    });
                    const apiData = await apiRes.json();
                    
                    if (apiData && apiData.code === 0 && apiData.data) {
                        videoDownloadUrl = apiData.data.hdplay || apiData.data.play || "";
                    }

                    if (processingMsg) {
                        await bot.deleteMessage(chatId, processingMsg.message_id).catch(() => {});
                    }

                    if (videoDownloadUrl) {
                        const videoRes = await fetch(videoDownloadUrl);
                        const arrayBuffer = await videoRes.arrayBuffer();
                        const videoBuffer = Buffer.from(arrayBuffer);
                        const sizeInMB = videoBuffer.length / (1024 * 1024);

                        if (sizeInMB <= 30) {
                            // Buffer and send video directly in chat
                            await bot.sendVideo(chatId, videoBuffer, {
                                caption: `<blockquote>📥 <b>Downloaded via TG Meta69 Bot</b>\n📊 Size: <code>${sizeInMB.toFixed(2)} MB</code>\n👨‍💻 Developer: @srshihab69</blockquote>`,
                                parse_mode: 'HTML'
                            }, {
                                filename: 'tiktok_video.mp4',
                                contentType: 'video/mp4'
                            });
                        } else {
                            // File larger than 30MB, send inline button download
                            await bot.sendMessage(chatId, 
                                `<blockquote>⚠️ <b>Video is larger than 30MB! (${sizeInMB.toFixed(2)} MB)</b>\n\n🔗 Click the button below to download the video directly from the browser. ✅</blockquote>`, 
                                { 
                                    parse_mode: 'HTML',
                                    reply_markup: {
                                        inline_keyboard: [
                                            [{ text: `📥 Download HD Video (${sizeInMB.toFixed(1)} MB)`, url: videoDownloadUrl }]
                                        ]
                                    }
                                }
                            );
                        }
                    } else {
                        await bot.sendMessage(chatId, `<blockquote>⚠️ <b>This link is not supported or video not found.</b></blockquote>`, { parse_mode: 'HTML' });
                    }
                } catch (apiErr) {
                    console.error("TikTok Video Error:", apiErr);
                    if (processingMsg) {
                        await bot.deleteMessage(chatId, processingMsg.message_id).catch(() => {});
                    }
                    await bot.sendMessage(chatId, `<blockquote>⚠️ <b>Failed to process TikTok video. Please try again.</b></blockquote>`, { parse_mode: 'HTML' });
                }
            }
            else {
                let fileObj = null;
                let fileTypeName = "file";

                if (msg.photo) {
                    fileObj = msg.photo[msg.photo.length - 1];
                    fileTypeName = "photo";
                } else if (msg.video) {
                    fileObj = msg.video;
                    fileTypeName = "video";
                } else if (msg.animation) {
                    fileObj = msg.animation;
                    fileTypeName = "gif";
                } else if (msg.sticker) {
                    fileObj = msg.sticker;
                    fileTypeName = "sticker";
                } else if (msg.document) {
                    fileObj = msg.document;
                    fileTypeName = "document";
                } else if (msg.audio) {
                    fileObj = msg.audio;
                    fileTypeName = "audio";
                } else if (msg.voice) {
                    fileObj = msg.voice;
                    fileTypeName = "voice";
                }

                if (fileObj && fileObj.file_id) {
                    const isForwarded = Boolean(msg.forward_date || msg.forward_from || msg.forward_from_chat || msg.forward_origin);
                    
                    if (!isForwarded) {
                        const pendingKey = `${chatId}_${msg.message_id}`;
                        pendingUploads.set(pendingKey, { fileId: fileObj.file_id, fileName: `${fileTypeName}_file`, fileType: fileTypeName });

                        await bot.sendMessage(chatId, 
                            `<blockquote>✨ <b>Media Detected Successfully!</b>\n\n🔐 <b>Do you want to secure this media with a password?</b></blockquote>`, 
                            {
                                parse_mode: 'HTML',
                                reply_markup: {
                                    inline_keyboard: [
                                        [{ text: '🔒 Set Password', callback_data: `pwd_ask_${msg.message_id}` }],
                                        [{ text: '🔓 No Password (Unprotected)', callback_data: `pwd_none_${msg.message_id}` }]
                                    ]
                                }
                            }
                        );
                    }
                }
            }
        }

    } catch (err) {
        console.error("Critical Error:", err);
    } finally {
        if (!res.headersSent) {
            res.status(200).send('OK');
        }
    }
});

async function processTelegramMediaShare(chatId, messageId, fileData, userObj, password) {
    try {
        const payloadId = `srmeta_${Math.random().toString(36).substring(2, 9)}`;

        const mediaObject = { 
            type: 'media', 
            fileId: fileData.fileId, 
            fileType: fileData.fileType, 
            user: userObj,
            payloadId
        };

        mediaStore.set(payloadId, mediaObject);

        if (password) {
            mediaPasswords.set(payloadId, password);
        }

        const currentBotUser = botUsername || process.env.BOT_USERNAME || 'YourBotUsername';
        const shareBotLinkUrl = `https://t.me/${currentBotUser}?start=${payloadId}`;

        const successText = `<blockquote>✅ <b>Telegram Share Link Generated Successfully!</b>\n\n` +
            (password ? `🔒 <b>Status:</b> Password Protected\n\n` : `🔓 <b>Status:</b> Unprotected\n\n`) +
            `✨ <b>Bot Start / Share Link:</b>\n` +
            `🔗 <code>${shareBotLinkUrl}</code></blockquote>`;

        await bot.sendMessage(chatId, successText, {
            parse_mode: 'HTML',
            reply_markup: {
                inline_keyboard: [
                    [
                        { text: '🤖 Open / Share Bot Link', url: shareBotLinkUrl }
                    ]
                ]
            }
        });
    } catch (e) {
        console.error("Share Link Generation Error:", e);
        await bot.sendMessage(chatId, `<blockquote>❌ <b>Generation Failed!</b> Please try sending the file again.</blockquote>`, { parse_mode: 'HTML' });
    }
}

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`TG Meta69Bot Active on Port ${PORT}`));
